spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/manage
    username: root
    password: Marine1235689412
    driver-class-name: com.mysql.cj.jdbc.Driver


sa-token:
  # token 名称
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），
  active-timeout: -1
  # 是否允许同一账号多地同时登录 
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true